<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<?php echo $this->headTitle('Actualizar Proveedor'); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl()."/style/compras.css")."\n"; ?>
	</head>
<body>
	<div class="wrapper">
		<div class="header">
			<div class="header-top">
				<?php include("session-data.phtml"); ?>
			</div>
			<?php include("menu.phtml"); ?>		
		</div>
		<?php if($this->proveedor){ ?>

		<?php if(isset($this->message)) { ?>
			<div class="notification">
				<div class="message">Mensaje: </div><span><?php echo $this->message; ?></span>
			</div>
		<?php } ?>
			<div class="content">
			</div>
			<?php header("refresh:1;url=visualizaproveedor"); ?>
		<?php }else{ ?> 
		<?php if(isset($this->message)) { ?>
			<div class="notification">
				<div class="message">Mensaje: </div><span><?php echo $this->message; ?></span>
			</div>
		<?php } ?>
			<div class="content">
				<div class="content-header">
					<div class="content-title"><span>Proveedor Nuevo - Hay Errores en el Formulario</span></div>
				</div>
				<div class="form-box">
					<div class="form-box-title"><span>Información Nuevo Proveedor</span></div>
					<div class="form-box-content">
						<?php if (isset($this->form)) { echo $this->form; } ?>
					</div>
				</div>
			</div>			
		<?php } ?>
		<div class="footer">
		</div>
	</div>
</body>
</html>