<div class="menu-top">
	<ul class="menu-nav">
		<li class="menu-nav-opt"><a href="altaproveedor"><span>Agregar Proveedores</span></a></li>
		<li class="menu-nav-opt"><a href="busquedasproveedor"><span>Buscar Proveedores</span></a></li>
		<li class="menu-nav-opt"><a href="visualizaproveedor"><span>Lista Proveedores</span></a></li>
		<li class="menu-nav-opt"><a href="index"><span>Regresar</span></a></li>
	</ul>
	<br/>
</div>