<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<?php echo $this->headTitle('Buscar Proveedor'); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl()."/style/compras.css")."\n"; ?>
	</head>
<body>
	<div class="wrapper">
		<div class="header">
			<div class="header-top">
				<?php include("session-data.phtml"); ?>
			</div>
			<?php include("menu.phtml"); ?>		
		</div>
		<?php if(isset($this->message)) { ?>
			<div class="notification">
				<div class="message">Mensaje: </div><span><?php echo $this->message; ?></span>
			</div>
		<?php } ?>
		<div class="content">
			<div class="content-header">
				<div class="content-title"><span>Resultado de Búsqueda</span></div>
			</div>
			<div id="message"><?php echo $this->message; ?></div>
			<div class="form-box">
				<div class="form-box-title"><span>Información del Proveedor Encontrado</span></div>
				<div class="form-box-content">
					<?php
						if($this->results){
					?>
						<table class="tableclass">
							<tr class="tab-header">
					    		<th class="tab-title">Número</th>
					    		<th class="tab-title">Nombre de Proveedor</th>
					    		<th class="tab-title">Teléfono</th>
								<th class="tab-title">Productos</th>
								<th class="tab-title">Actualizar</th>
							</tr>
							<?php
								foreach($this->results as $result){
							?>
								<tr class="tab-info">
					    			<td class="tab-midinfo"><?php echo $result['id_proveedor']; ?></td>
					    			<td class="tab-midinfo"><?php echo $result['nombre']; ?></td>	
					    			<td class="tab-midinfo"><?php echo $result['tel']; ?></td>
									<td class="tab-smallinfo"><a href="verproductosprov?id_prov=<?php echo $result['id_proveedor']; ?>">Ver Productos</a></td>
									<td class="tab-smallinfo"><a href="modificaproveedor?id_prov=<?php echo $result['id_proveedor']; ?>">Modificar</a></td>
								</tr>
							<?php
								}
							?>
						</table>	
					<?php	
						}else{
					?> 
						<div>No hay datos </div>
					<?php
						}
					?>
				</div>
			</div>
		</div>
		<div class="footer">
		</div>
	</div>
</body>
</html>