<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<?php echo $this->headTitle('Visualización de Productos de Proveedor'); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl()."/style/compras.css")."\n"; ?>
	</head>
<body>
	<div class="wrapper">
		<div class="header">
			<div class="header-top">
				<?php include("session-data.phtml"); ?>
			</div>
			<?php include("menu.phtml"); ?>		
		</div>
		<?php if(isset($this->message)) { ?>
			<div class="notification">
				<div class="message">Mensaje: </div><span><?php echo $this->message; ?></span>
			</div>
		<?php } ?>
		<div class="content">
			<div class="content-header">
				<div class="content-title"><span>Visualización de Productos</span></div>
			</div>
			<div class="form-box">
				<div class="form-box-title"><span>Información de Proveedor</span></div>
				<div class="form-box-content">
					<?php foreach($this->proveedor as $proveedor){ ?>
						<div class="row-info">
	    					<div class="infolabel">Número:</div><div class="div-smallinfo"><span><?php echo $proveedor['id_proveedor']; ?></span></div>
	    					<div class="infolabel">Nombre:</div><div class="div-largeinfo"><span><?php echo $proveedor['nombre']; ?></span></div>
	    					<div class="infolabel">Teléfono:</div><div class="div-midinfo"><span><?php echo $proveedor['tel']; ?></span></div>
							<div class="infolabel">Contacto:</div><div class="div-midinfo"><?php echo $proveedor['contacto']; ?></div>
						</div>
						<div class="row-info">
							<div class="infolabel">País:</div><div class="div-smallinfo"><span><?php echo $proveedor['pais']; ?></span></div>
							<div class="infolabel">Domicilio:</div><div class="div-largeinfo"><span><?php echo $proveedor['domicilio']; ?></span></div>
							<div class="infolabel">R.F.C.:</div><div class="div-midinfo"><span><?php echo $proveedor['rfc']; ?></span></div>
							<div class="infolabel">Correo:</div><div class="div-midinfo"><span><?php echo $proveedor['mail']; ?></span></div>
						</div>
						<div class="row-info">
							<div class="infolabel">Crédito:</div><div class="div-smallinfo"><span><?php echo $proveedor['credito']; ?></span></div>
							<div class="infolabel">ICOTERM:</div><div class="div-largeinfo"><span><?php echo $proveedor['icoterm']; ?></span></div>
							<div class="infolabel">Moneda:</div><div class="div-midinfo"><span><?php echo $proveedor['moneda']; ?></span></div>
							<div class="infolabel">Sitio-Web:</div><div class="div-midinfo"><span><?php echo $proveedor['pag_web']; ?></span></div>
						</div>
						<div class="row-info">
							<div class="infolabel">Distribución Exclusiva:</div><div class="div-largeinfo"><span><?php echo $proveedor['distr_exclusiva']; ?></span></div>
						</div>						
						<?php } ?>
				</div>
			</div>
			<div class="form-box">
				<div class="form-box-title"><span>Información de Productos en Lista del Proveedor</span></div>
				<div class="form-box-content">
					<?php
						if($this->existences){
					?>
					<table class="tableclass">
						<tr class="tab-header">
		    				<th class="tab-title">C&oacute;digo Interno</th>
		    				<th class="tab-title">Cantidad</th>
		    				<th class="tab-title">Modelo</th>
		    				<th class="tab-title">Marca</th>
		    				<th class="tab-title">Pieza</th>
							<th class="tab-title">Tipo</th>
						</tr>
						<?php
							foreach($this->existences as $result){
						?>
							<tr class="tab-info">
		    					<td class="tab-midinfo"><?php echo $result['codigo_interno']; ?></td>
		    					<td class="tab-midinfo"><?php echo $result['existencia']; ?></td>
		    					<td class="tab-midinfo"><?php echo $result['modelo']; ?></td>	
		    					<td class="tab-midinfo"><?php echo $result['marca']; ?></td>
		    					<td class="tab-midinfo"><?php echo $result['pieza']; ?></td>
		    					<td class="tab-midinfo"><?php echo $result['tipo']; ?></td>
							</tr>
						<?php
							}
						?>
					</table>
					<?php	
						}else{
					?> 
						<div>No hay datos </div>
					<?php
						}
					?>
				</div>	
			</div>	
		</div>
		<div class="footer">
		</div>
	</div>
</body>
</html>