<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<?php echo $this->headTitle('Visualización de Productos'); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl()."/style/compras.css")."\n"; ?>
	</head>
<body>
	<div class="wrapper">
		<div class="header">
			<div class="header-top">
				<?php include("session-data.phtml"); ?>
			</div>
			<?php include("menu.phtml"); ?>		
		</div>
		<?php if(isset($this->message)) { ?>
			<div class="notification">
				<div class="message">Mensaje: </div><span><?php echo $this->message; ?></span>
			</div>
		<?php } ?>
		<div class="content">
			<div class="content-header">
				<div class="content-title"><span>Visualización de Proveedores</span></div>
			</div>
			<div class="form-box">
				<div class="form-box-title">
					<form method="post">
					<span>Información de Proveedores en Lista</span>
					<div id="options">
						<label for="accion">Acciones: </label>
						<select name="accion" id="accion">
							<option value="delete">Eliminar</option>
						</select>
					</div>
					<input type="submit" class="action" name="action" value="Enviar" style="margin: 4px 10px;"/>
					</form>					
				</div>
				<div class="form-box-content">
					<?php
						if($this->results){
					?>
						<table class="tableclass">
							<tr class="tab-header">
								<th class="tab-title"> </th>
					    		<th class="tab-title">Número</th>
					    		<th class="tab-title">Nombre de Proveedor</th>
					    		<th class="tab-title">Teléfono</th>
								<th class="tab-title">Productos</th>
								<th class="tab-title">Actualizar</th>
							</tr>
							<?php
								foreach($this->results as $result){
							?>
								<tr class="tab-info">
									<td class="tab-smallinfo">
										<input type="checkbox" name="act_check[]" class="act_check" value="<?php echo $result['id_proveeor']; ?>" />
									</td>
					    			<td class="tab-midinfo"><?php echo $result['id_proveedor']; ?></td>
					    			<td class="tab-midinfo"><?php echo $result['nombre']; ?></td>	
					    			<td class="tab-midinfo"><?php echo $result['tel']; ?></td>
									<td class="tab-smallinfo"><a href="verproductosprov?id_prov=<?php echo $result['id_proveedor']; ?>">Ver Productos</a></td>
									<td class="tab-smallinfo"><a href="modificaproveedor?id_prov=<?php echo $result['id_proveedor']; ?>">Modificar</a></td>
								</tr>
							<?php
								}
							?>
						</table>	
					<?php	
						}else{
					?> 
						<div>No hay datos </div>
					<?php
						}
					?>
				</div>
			</div>
		</div>
		<div class="footer">
		</div>
	</div>
</body>
</html>