<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html lang="en">
<head>
<?php echo $this->headTitle('Ver todas las cuentas'); ?>
</head>
<body>
<h2>Lista de Usuarios Activos</h2>
<table width="300" border="1">
<?php if($this->users){ ?>
<tr align="center">
<td><b>Nombre de Usuario</b></td>
<td><b>Contraseña</b></td>
</tr>
<?php
foreach($this->users as $user){
?>
<tr>
	<td><?php echo $user['username']?></td>
	<td><?php echo $user['password']?></td>
</tr>
<?php
}
}else{
?>
<tr>
<td>No existe ningún usuario en el sistema.</td>
</tr>
<?php
}
?>
</table>
</body>
</html>