<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<?php echo $this->headTitle('ERP Nueva Orden de Salida'); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl()."/style/almacen.css")."\n"; ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl()."/style/special.css")."\n"; ?>
	</head>
	
<body>
	<div class="wrapper">
		<div class="header">
			<div class="header-top">
				<?php include("session-data.phtml"); ?>
			</div>
			<?php include("menu.phtml"); ?>		
		</div>		
		<?php if($this->message) { ?>
			<div class="notification">
				<div class="message">Mensaje: </div><span><?php echo $this->message; ?></span>
			</div>
		<?php } ?>
		<div class="content">
			<div class="content-header">
				<div class="content-title"><span>Nueva Orden de Salida</span></div>
			</div>
			<div class="form-box">
				<div class="form-box-title"><span>Agrega los números de serie</span></div>
				<div class="form-box-content">
					<?php
						echo $this->form;
					?>
					<br />
					<?php
						if($this->form2 && $this->productos){
					?>
					<form action="add-salida-productos" method="POST">
					<table class="tableclass">
						<tr class="tab-header">
		    				<th class="tab-title">Cantidad</th>
		    				<th class="tab-title">Descripción</th>
		    				<th class="tab-title">C&oacute;digo Interno</th>
		    				<th class="tab-title">Serie</th>
		    				<th class="tab-title"> </th>
		    			<!--	<th class="tab-title">Unitario</th>
							<th class="tab-title">Costo</th> -->
						</tr>
						<?php
							if($this->productos){
								$i=0;
								$productos_orden = $this->productos;
								$items = $productos_orden['items'];
								for($x=1;$x<=$items;$x++){
									$res=$i%2; 
									if($res==0){
						?>
						<tr class="tab-info">
						  <?php 	}else{ ?>						
						<tr class="tab-info2">
						  <?php 	} ?>
													
		    				<td class="tab-smallinfo"><?php $cantidad = $productos_orden[$x]['cantidad']; echo $cantidad; ?></td>
		    				<td class="tab-largeinfo"><?php echo $productos_orden[$x]['descripcion']; ?></td>
		    				<td class="tab-midinfo"><?php echo $productos_orden[$x]['codigo_interno']; ?></td>	 
		    				<td class="tab-tinyinfo" id="tab-series">
		    					<?php
		    						for($z=1;$z<=$cantidad;$z++) 
		    						  echo $productos_orden[$x]['serie'][$z]."<br/>"; 
		    					?>
		    				</td>
		    				<td class="tab-tinyinfo">
		    					<a href="/almacen/add-salida-productos?eliminar=<?php echo $x; ?>">Eliminar</a>
		    				</td>
		    				<!-- <td class="tab-smallinfo"><?php echo $productos_orden[$x]['unitario']; ?></td>
		    				<td class="tab-smallinfo"><?php echo $productos_orden[$x]['costo']; ?></td> -->
						</tr>
						
						<?php  		$i++; 
								}
							}
						?>	
					</table>
					</form>
					<?php	
							echo $this->form2;
						}
					?> 
				</div>
			</div>
		</div>
		<div class="footer">
		</div>
	</div>
</body>
</html>