<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<?php echo $this->headTitle('ERP Busca Producto'); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl()."/style/almacen.css")."\n"; ?>
	</head>
	
<body>
	<div class="wrapper">
		<div class="header">
			<div class="header-top">
				<?php include("session-data.phtml"); ?>
			</div>
			<?php include("menu.phtml"); ?>		
		</div>
		<?php if(isset($this->message)) { ?>
			<div class="notification">
				<div class="message">Mensaje: </div><span><?php echo $this->message; ?></span>
			</div>
		<?php } ?>
		<?php if(!$this->form){?>
		<div class="content">
		<?php } else { ?>
		<div class="content" style="width:60%">
		<?php } ?>
			<div class="content-header">
				<div class="content-title"><span>Existencias de Productos</span></div>
			</div>
			<div class="form-box">
				<?php if($this->obj){ ?>
						<h3> Existencia modificada correctamente </h3>
						<?php header("refresh:1;url=existencias"); ?>
				<?php }else{ ?>
				<div class="form-box-title"><span>Agregar Existencia al Producto <?php echo $_REQUEST['cod_int']; ?></span></div>
					<div class="form-box-content">
						<div id="form-series">
							<?php echo $this->form; ?>
						</div>
					</div>
				<?php } ?>
				<br/>
			</div>
		</div>
		<div class="footer">
		</div>
	</div>
</body>
</html>