<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<?php echo $this->headTitle('ERP Nueva Orden de Salida'); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl()."/style/almacen.css")."\n"; ?>
	</head>
	
<body>
	<div class="wrapper">
		<div class="header">
			<div class="header-top">
				<?php include("session-data.phtml"); ?>
			</div>
			<?php include("menu.phtml"); ?>		
		</div>		
		<?php if($this->messageUser) { ?>
			<div class="notification">
				<div class="message">Mensaje: </div><span><?php echo $this->messageUser; ?></span>
			</div>
		<?php } ?>
		<div class="content">
			<div class="content-header">
				<div class="content-title"><span>Modificar Estatus de Productos</span></div>
			</div>
			<div class="form-box">
				<div class="form-box-title"><span>Estatus de Serie Producto</span></div>
				<div class="form-box-content">
					<?php 
					if(isset($this->form1)):
							echo $this->form1;
					else:
						
						if(isset($this->info_serie)):
						$info_serie = $this->info_serie;
					?>
					<form action="cambiar-estatus-producto" method="POST">
						<table class="tableclass">
							<tr class="tab-header">
		    					<th class="tab-title">Id Producto</th>
		    					<th class="tab-title">Número Serie</th>
		    					<th class="tab-title">Almacen</th>
		    					<th class="tab-title">Zona</th>
		    					<th class="tab-title">Estatus</th>
		    					<th class="tab-title">Seminuevo</th>
							</tr>
						<?php
						 // YTRH-109JK
						?>					
							<tr class="tab-info2">			
		    					<td class="tab-smallinfo"><?php echo $info_serie['id_producto']; ?></td>
		    					<td class="tab-largeinfo"><?php echo $info_serie['numero_serie']?></td>
		    					<td class="tab-tinyinfo"><?php  echo $info_serie['almacen']; ?></td>	 
		    					<td class="tab-tinyinfo"><?php echo $info_serie['zona']; ?></td>
		    					<td class="tab-tinyinfo"><?php echo $info_serie['id_status']; ?></td>
		    					<td class="tab-tinyinfo"><?php echo $info_serie['seminuevo']; ?></td>
							</tr>
						</table>
					</form>
				<?php  		
					endif;
						if($this->form2){echo $this->form2;}
				 endif;	
				?>	
				</div>
			</div>
		</div>
		<div class="footer">
		</div>
	</div>
</body>
</html>