<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<?php echo $this->headTitle('Existencias de Productos'); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl()."/style/almacen.css")."\n"; ?>
	</head>
<body>
	<div class="wrapper">
		<div class="header">
			<div class="header-top">
				<?php include("session-data.phtml"); ?>
			</div>
			<?php include("menu.phtml"); ?>		
		</div>
		<?php if($this->message) { ?>
			<div class="notification">
				<div class="message">Mensaje: </div><span><?php echo $this->message; ?></span>
			</div>
		<?php } ?>
		<div class="content">
			<div class="content-header">
				<div class="content-title"><span>Visualización de Existencias</span></div>
			</div>
			<div class="form-box">
				<div class="form-box-title"><span>Información de Existencias de Productos en Lista</span></div>
				<div class="form-box-content">
					<?php
						echo $this->form;
					?>
					<div class="existences">
						<input type="button" id="submit-existencias" value="Agregar Existencias" onclick="window.location.href='existenciadir'" />
					</div>
					<?php
						if($this->existences){
					?>
						<table class="tableclass">
							<tr class="tab-header">
								<th class="tab-title">Agregar</th>
		    					<th class="tab-title">Código Interno</th>
		    					<th class="tab-title">Descripción</th>
		    					<th class="tab-title">Modelo</th>
		    					<th class="tab-title">Marca</th>
		    					<th class="tab-title">Pieza</th>
								<th class="tab-title">Tipo</th>
		    					<th class="tab-title">Cantidad</th>
								<th class="tab-title">Series</th>
							</tr>
							<?php
								foreach($this->existences as $result){
							?>
							<tr class="tab-info">
								<td class="tab-smallinfo"><a href="existenciaind?cod_int=<?php echo $result['codigo_interno']; ?>">Agregar</a></td>
		    					<td class="tab-midinfo"><?php echo $result['codigo_interno']; ?></td>
		    					<td class="tab-midinfo"><?php echo $result['descripcion']; ?></td>	
		    					<td class="tab-midinfo"><?php echo $result['modelo']; ?></td>	
		    					<td class="tab-midinfo"><?php echo $result['marca']; ?></td>
		    					<td class="tab-smallinfo"><?php echo $result['pieza']; ?></td>
		    					<td class="tab-midinfo"><?php echo $result['tipo']; ?></td>
		    					<td class="tab-largeinfo"><?php echo $result['existencia']; ?></td>
		    					<td class="tab-smallinfo"><a href="ver-series?id_producto=<?php echo $result['id_producto']; ?>">Series</a></td>
							</tr>
							<?php
								}
							?>
						</table>	
					<?php	
						}else{
					?> 
						<!-- <div> No hay datos </div> -->
		
					<?php
						}
					?>
				</div>	
			</div>	
		</div>
		<div class="footer">
		</div>
	</div>
</body>
</html>