<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<?php echo $this->headTitle('ERP Existencia por Código de Producto'); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl()."/style/almacen.css")."\n"; ?>
	</head>	
<body>
	<div class="wrapper">
		<div class="header">
			<div class="header-top">
				<?php include("session-data.phtml"); ?>
			</div>
			<?php include("menu.phtml"); ?>		
		</div>
		<?php if(isset($this->message)) { ?>
			<div class="notification">
				<div class="message">Mensaje: </div><span><?php echo $this->message; ?></span>
			</div>
		<?php } ?>
		<?php if(!$this->formSeriesProd){ ?>
			<div class="content" style="width:54%">
		<?php } else { ?>
			<div class="content" style="width:31.5%">
		<?php } ?>
			<div class="content-header">
				<div class="content-title"><span>Modificación de Existencia</span></div>
			</div>
			<div class="form-box">
				<div class="form-box-title"><span>Agregar Existencia al Producto</span></div>
				<div class="form-box-content">
					<?php echo $this->form; ?>
					<div id="form-series">
					<?php echo $this->formSeriesProd;?>
					</div>
				</div>
			</div>
		</div>
		<div class="footer">
		</div>
	</div>
</body>
</html>
