<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<?php echo $this->headTitle('ERP Modulo Almacén'); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl()."/style/almacen.css")."\n"; ?>
	</head>
<body>
	<div class="wrapper">
		<div class="header">
			<div class="header-top">
				<?php include("session-data.phtml"); ?>
			</div>
			<?php include("menu.phtml"); ?>		
		</div>
		<?php if(isset($this->message)) { ?>
			<div class="notification">
				<div class="message">Mensaje: </div><span><?php echo $this->message; ?></span>
			</div>
		<?php } ?>
		<div class="navegation">
			<a href="/almacen/lista-orden-salida">Visualizar Salidas</a>
		</div>
		<div class="content" style="width:800px">
			<div class="content-header">
				<div class="content-title"><span>Visualización de Productos de Salidas</span></div>
			</div>
			<div class="form-box">
				<form action="visualizaproducto" method="post">
				<div class="form-box-title">
					<span>Información de Productos de Orden de Salida <?php echo $this->id_orden; ?></span>
				</div>
				<div class="form-box-content">
					<?php	if($this->lista){ ?>
					<table class="tableclass">
						<tr class="tab-header">
						<tr class="tab-header">
		    				<th class="tab-title">Cantidad</th>
		    				<th class="tab-title">Descripción</th>
		    				<th class="tab-title">C&oacute;digo Interno</th>
		    				<th class="tab-title">Serie</th>
						</tr>
						</tr>
						<?php
							$i=0;
							foreach($this->lista as $result){
								$res=$i%2; 
								if($res==0){
							?>
								<tr class="tab-info">
							<?php }else{?>
								<tr class="tab-info2">
							<?php } ?>
		    					<td class="tab-smallinfo"><?php echo $result['cantidad']; ?></td>
		    					<td class="tab-largeinfo"><?php echo $result['descripcion']; ?></td>	
		    					<td class="tab-smallinfo"><?php echo $result['codigo']; ?></td>
		    					<td class="tab-smallinfo"><?php echo $result['series']; ?></td>
							</tr>
						<?php
								$i++;
							}
						?>
					</table>
					<?php	
						}else{
					?> 
						<div>No hay datos </div>
					<?php
						}
					?>
				</div>	
				</form>
			</div>	
		</div>
		<div class="footer">
		</div>
	</div>
</body>
</html>