<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<?php echo $this->headTitle('Buscar Producto'); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl()."/style/almacen.css")."\n"; ?>
	</head>
<body>
	<div class="wrapper">
		<div class="header">
			<div class="header-top">
				<?php include("session-data.phtml"); ?>
			</div>
			<?php include("menu.phtml"); ?>		
		</div>
		<?php if(isset($this->message)) { ?>
			<div class="notification">
				<div class="message">Mensaje: </div><span><?php echo $this->message; ?></span>
			</div>
		<?php } ?>
		<div class="content">
			<div class="content-header">
				<div class="content-title"><span>Resultado de Búsqueda</span></div>
			</div>
			<div id="message"><?php echo $this->message; ?></div>
			<div class="form-box">
				<div class="form-box-title"><span>Información del Producto a Encontrado</span></div>
				<div class="form-box-content">
					<?php
						if($this->results){
					?>
						<table class="tableclass">
							<tr class="tab-header">
					    		<th class="tab-title">C&oacute;digo Interno</th>
					    		<th class="tab-title">Modelo</th>
					    		<th class="tab-title">Marca</th>
					    		<th class="tab-title">Descripci&oacute;n</th>
					    		<th class="tab-title">Pieza</th>
								<th class="tab-title">Tipo</th>
							</tr>
							<?php
								foreach($this->results as $result){
							?>
								<tr class="tab-info">
					    			<td class="tab-midinfo"><?php echo $result['codigo_interno']; ?></td>
					    			<td class="tab-midinfo"><?php echo $result['modelo']; ?></td>	
					    			<td class="tab-midinfo"><?php echo $result['marca']; ?></td>
					    			<td class="tab-largeinfo"><?php echo $result['descripcion']; ?></td>
					    			<td class="tab-smallinfo"><?php echo $result['pieza']; ?></td>
					    			<td class="tab-midinfo"><?php echo $result['tipo']; ?></td>
								</tr>
							<?php
								}
							?>
						</table>	
					<?php	
						}else{
							echo $this->form;
					?> 
					<div>No hay datos </div>

					<?php
						}
					?>
				</div>
			</div>
		</div>
		<div class="footer">
		</div>
	</div>
</body>
</html>