<?php echo $this->doctype('XHTML1_STRICT'); ?>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<?php echo $this->headTitle('Visualización de Usuarios'); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl()."/style/admin.css")."\n"; ?>
	</head>
<body>
	<div class="wrapper">
		<div class="header">
			<div class="header-top">
				<?php include("session-data.phtml"); ?>
			</div>
			<?php include("menu.phtml"); ?>		
		</div>
		<?php if($this->message) { ?>
			<div class="notification">
				<div class="message">Mensaje: </div><span><?php echo $this->message; ?></span>
			</div>
		<?php } ?>
		<div class="content">
			<div class="content-header">
				<div class="content-title"><span>Actualiza Rol de Usuario</span></div>
			</div>
			<div class="form-box">
				<div class="form-box-title">
					<span>Selecciona la Opción del Rol</span>
					<div id="lista-usuarios">
						<input type="button" id="submit" value="Ver Usuarios" onclick="window.location.href='/admin/ver-usuarios'" />
					</div>
				</div>
				<div class="form-box-content">
					<?php echo $this->setrolform; ?>
				</div>
			</div>
		</div>
		<div class="footer"> </div>
	</div>
</body>
</html>

	
